//! Frozen expectations are never regenerated by the engine under test.

#[test]
fn frozen_inputs_and_oracles_match_their_provenance_checksums() {
    let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures");
    let count = ct_test_support::fixture_archive::verify_compat(&root).unwrap();
    assert_eq!(count, 130, "冻结输入/期望值的范围不可静默缩减");
}
