/*
 * gd_native.h
 *
 * Hand-written reference implementation for loading GD binary data bundles.
 * This file is NOT generated by the ct export tool. It is provided as a
 * reference for integrating GD binary bundles into a C/C++ runtime.
 *
 * The API exposes a simple lifecycle:
 *   1. GD_Load()        - read binary files into memory
 *   2. GD_GetMainBytes  - get pointer to main data bundle
 *   3. GD_GetI18nBytes  - get pointer to i18n data bundle
 *   4. GD_Unload()      - free memory
 *
 * Usage example (C):
 *   GD_Load("output/binary/data_zh.bin", "output/binary/data_en.bin");
 *   size_t main_size;
 *   const void* main_data = GD_GetMainBytes(&main_size);
 *   // ... use main_data with FlatBuffers ...
 *   GD_Unload();
 */

#ifndef GD_NATIVE_H
#define GD_NATIVE_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Load the main data bundle and (optionally) the i18n data bundle
 * from the given file paths into memory.
 *
 * @param main_path  Path to the main binary bundle (e.g. "data_zh.bin").
 *                   Must not be NULL.
 * @param i18n_path  Path to the i18n binary bundle (e.g. "data_en.bin").
 *                   May be NULL if no i18n bundle is needed.
 */
void GD_Load(const char* main_path, const char* i18n_path);

/*
 * Get a pointer to the loaded main data bytes.
 *
 * @param out_size  If non-NULL, receives the size of the data in bytes.
 * @return          Pointer to the raw FlatBuffers data, or NULL if not loaded.
 *                  The pointer remains valid until GD_Unload() is called.
 */
const void* GD_GetMainBytes(size_t* out_size);

/*
 * Get a pointer to the loaded i18n data bytes.
 *
 * @param out_size  If non-NULL, receives the size of the data in bytes.
 * @return          Pointer to the raw FlatBuffers data, or NULL if not loaded.
 *                  The pointer remains valid until GD_Unload() is called.
 */
const void* GD_GetI18nBytes(size_t* out_size);

/*
 * Free all loaded data and reset internal state.
 * Safe to call even if GD_Load() was never called.
 */
void GD_Unload();

#ifdef __cplusplus
}
#endif

#endif /* GD_NATIVE_H */
