//! FBS 文本生成（`ct/export/canonical_fbs.py`）：
//! 共享 types.fbs（确定性依赖序）+ 每表 fbs + 结构检查。

use std::collections::{BTreeMap, HashMap};

use ct_domain::repository::Resource;
use ct_domain::schema::TableResource;
use ct_domain::types::TypeExpr;

/// flatbuffers 标准标量名。
fn fbs_scalar(name: &str) -> Option<&'static str> {
    Some(match name {
        "int8" => "byte",
        "uint8" => "ubyte",
        "int16" => "short",
        "uint16" => "ushort",
        "int32" => "int",
        "uint32" => "uint",
        "int64" => "long",
        "uint64" => "ulong",
        "float" => "float32",
        "double" => "float64",
        "bool" => "bool",
        "string" => "string",
        _ => return None,
    })
}

fn fbs_type(type_expr: &TypeExpr) -> String {
    match type_expr {
        TypeExpr::Scalar(name) => fbs_scalar(name).expect("未知标量").to_string(),
        TypeExpr::Named(named) => named.name().to_string(),
        TypeExpr::Vector(element) => format!("[{}]", fbs_type(element)),
    }
}

/// 共享 types.fbs：按依赖序发射 Record/Enum，每类一次。
pub fn types_fbs_text(order: &[String], resources: &BTreeMap<String, Resource>) -> String {
    let mut lines: Vec<String> = Vec::new();
    for resource_id in order {
        let Some(resource) = resources.get(resource_id) else {
            continue;
        };
        match resource {
            Resource::Enum(enum_) => {
                let entries: Vec<String> = enum_
                    .values
                    .iter()
                    .enumerate()
                    .map(|(i, item)| format!("{} = {i}", item.name))
                    .collect();
                lines.push(format!(
                    "enum {} : byte {{ {} }}",
                    enum_.name,
                    entries.join(", ")
                ));
                lines.push(String::new());
            }
            Resource::Record(record) => {
                lines.push(format!("table {} {{", record.name));
                for field in &record.fields {
                    lines.push(format!("  {}: {};", field.name, fbs_type(&field.type_expr)));
                }
                lines.push("}".to_string());
                lines.push(String::new());
            }
            Resource::Table(_) => {}
        }
    }
    lines.join("\n")
}

/// 单表 fbs：自身 + 索引容器 + root。
pub fn table_fbs_text(table: &TableResource) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push("// Auto-generated by ct/export/canonical_fbs.py  DO NOT EDIT".to_string());
    lines.push("include \"types.fbs\";".to_string());
    lines.push(String::new());
    lines.push(format!("table {} {{", table.table));
    for field in table.client_fields() {
        lines.push(format!("  {}: {};", field.name, fbs_type(&field.type_expr)));
    }
    lines.push("}".to_string());
    lines.push(String::new());
    if table.primary_key().is_some() {
        lines.push("struct IndexEntry {".to_string());
        lines.push("  id: int32;".to_string());
        lines.push("  row: int32;".to_string());
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // 稀疏 i18n 表（行序与主表一致）
    let i18n_fields: Vec<_> = table.i18n_fields().filter(|f| !f.server_only).collect();
    if !i18n_fields.is_empty() && table.primary_key().is_some() {
        lines.push(format!("table {}I18nEntry {{", table.table));
        lines.push(format!("  {}: int32;", table.primary));
        for field in &i18n_fields {
            lines.push(format!("  {}: {};", field.name, fbs_type(&field.type_expr)));
        }
        lines.push("}".to_string());
        lines.push(String::new());
        lines.push(format!("table {}I18nTable {{", table.table));
        lines.push(format!("  items: [{}I18nEntry];", table.table));
        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.push(format!("table {}Table {{", table.table));
    lines.push(format!("  items: [{}];", table.table));
    if table.primary_key().is_some() {
        lines.push("  index: [IndexEntry];".to_string());
        lines.push("  idHash: [int32];".to_string());
    }
    if !table.indexes.is_empty() {
        lines.push("  codeNameIndex: [int32];".to_string());
    }
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push(format!("root_type {}Table;", table.table));
    lines.push(String::new());
    lines.join("\n")
}

/// 结构检查：重复符号 / 缺失共享类型 / Record 必须是 table / types.fbs 不得 include。
pub fn validate_canonical_fbs(
    types_text: &str,
    table_texts: &HashMap<String, String>,
    resources: &[Resource],
) -> Result<(), String> {
    if types_text.contains("include") {
        return Err("types.fbs 不得 include 其他文件（不允许 include 环）".to_string());
    }

    let decl = |text: &str| -> Vec<(String, String)> {
        let mut out = Vec::new();
        for line in text.lines() {
            let trimmed = line.trim_start();
            for kind in ["enum", "table", "struct"] {
                if let Some(rest) = trimmed.strip_prefix(kind) {
                    let rest = rest.trim_start();
                    let name: String = rest
                        .chars()
                        .take_while(|c| c.is_alphanumeric() || *c == '_')
                        .collect();
                    if !name.is_empty() {
                        out.push((kind.to_string(), name));
                    }
                    break;
                }
            }
        }
        out
    };

    let types_decl: HashMap<String, String> =
        decl(types_text).into_iter().map(|(k, n)| (n, k)).collect();
    let mut seen = std::collections::HashSet::new();
    let mut duplicates = Vec::new();
    for (_, name) in decl(types_text) {
        if !seen.insert(name.clone()) && !duplicates.contains(&name) {
            duplicates.push(name);
        }
    }
    if !duplicates.is_empty() {
        duplicates.sort();
        return Err(format!("types.fbs 存在重复符号: {}", duplicates.join(", ")));
    }

    for resource in resources {
        match resource {
            Resource::Enum(e) => {
                if types_decl.get(&e.name).map(String::as_str) != Some("enum") {
                    return Err(format!("共享 Enum '{}' 未在 types.fbs 声明为 enum", e.name));
                }
            }
            Resource::Record(r) => {
                let kind = types_decl.get(&r.name).map(String::as_str);
                if kind != Some("table") {
                    return Err(format!(
                        "共享 Record '{}' 必须生成 FlatBuffers table，当前为 {}",
                        r.name,
                        kind.unwrap_or("缺失")
                    ));
                }
            }
            Resource::Table(_) => {}
        }
    }

    for (table_name, table_text) in table_texts {
        for (_, name) in decl(table_text) {
            if types_decl.contains_key(&name) {
                return Err(format!(
                    "{table_name}.fbs 重复定义了共享类型 '{name}'（应通过 include 引用）"
                ));
            }
        }
    }
    Ok(())
}
