"""Task 8.8 -- Generate {Table}Accessor.cs files for each config table.

The generated C# static class provides zero-GC accessor methods that
read FlatBuffers data in-place for scalars and return pre-materialized
strings from arrays built during ``Preload()``.
"""

from __future__ import annotations

from pathlib import Path

from ct.export.accessor_model import build_accessor_model
from ct.schema.models import FieldDef, TableSchema




# Schema type -> C# type used in accessor return values
_CS_TYPE_MAP: dict[str, str] = {
    "int32": "int",
    "int64": "long",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "string": "string",
    "enum": "byte",
}

def _cs_return_type(field: FieldDef) -> str:
    """Return the C# type string for a field's accessor return value."""
    if field.type == "array":
        elem_type = _CS_TYPE_MAP.get(field.element or "", "int")
        if field.element == "enum":
            elem_type = "byte"
        return f"{elem_type}[]"
    if field.type == "struct":
        return f"{field.name}Struct"  # FlatBuffers table type
    return _CS_TYPE_MAP.get(field.type, "int")


# ---- code generation --------------------------------------------------------

def generate_csharp_accessor(schema: TableSchema, output_dir: Path) -> Path:
    """Generate ``{Table}Accessor.cs`` and write it to *output_dir*.

    Returns the path of the generated file.
    """
    model = build_accessor_model(schema)
    output_dir.mkdir(parents=True, exist_ok=True)

    table_pascal = schema.table
    class_name = f"{table_pascal}Accessor"

    # Collect non-server_only fields
    client_fields: list[FieldDef] = model.client_fields

    # Determine primary key info
    pk = model.primary
    pk_cs_type = _CS_TYPE_MAP.get(pk.type, "int")

    lines: list[str] = []
    w = lines.append  # shorthand

    # -- file header ----------------------------------------------------------
    w("// <auto-generated/>")
    w("// Generated by ct/export/csharp_accessor_generator.py -- DO NOT EDIT")
    w("")
    w("using System;")
    w("using System.Collections.Generic;")
    w("using Google.FlatBuffers;")
    w("")
    w(f"public static class {class_name}")
    w("{")

    # -- private state --------------------------------------------------------
    w("    private static ByteBuffer _bb;")
    w(f"    private static Dictionary<{pk_cs_type}, int> _mainIndex;")

    # String field indices (among client_fields) for pre-materialisation
    string_fields = model.string_fields
    for sf in string_fields:
        arr_name = f"_str_{sf.name}"
        w(f"    private static string[] {arr_name};")

    if schema.has_i18n:
        w("")
        w("    private static ByteBuffer _i18nBb;")
        w(f"    private static Dictionary<{pk_cs_type}, int> _i18nIndex;")
        for sf in model.i18n_fields:
            w(f"    private static string[] _i18nStr_{sf.name};")

    w("")

    # -- _FindTableBytes ------------------------------------------------------
    w("    private static ByteBuffer _FindTableBytes(ByteBuffer bundleBb, string tableName)")
    w("    {")
    w("        var bundle = DataBundle.GetRootAsDataBundle(bundleBb);")
    w("        for (int i = 0; i < bundle.TablesLength; i++)")
    w("        {")
    w("            var bt = bundle.Tables(i).Value;")
    w("            if (bt.Name == tableName)")
    w("            {")
    w("                int len = bt.DataLength;")
    w("                byte[] data = new byte[len];")
    w("                for (int j = 0; j < len; j++)")
    w("                    data[j] = bt.Data(j);")
    w("                return new ByteBuffer(data);")
    w("            }")
    w("        }")
    w("        throw new InvalidOperationException($\"Table '{tableName}' not found in config bundle.\");")
    w("    }")
    w("")

    # -- Preload --------------------------------------------------------------
    w("    public static void Preload()")
    w("    {")
    if schema.has_i18n:
        w("        // Reset i18n fields (reload-safe: Preload may be called to switch language)")
        w("        _i18nBb = null;")
        w(f"        _i18nIndex = null;")
        for sf in model.i18n_fields:
            w(f"        _i18nStr_{sf.name} = null;")
        w("")
    w("        // ---- main bundle ----")
    w("        byte[] mainBytes = GDNative.GetMainBytes();")
    w("        var bundleBb = new ByteBuffer(mainBytes);")
    w(f'        _bb = _FindTableBytes(bundleBb, "{schema.table}");')
    w(f"        var root = {table_pascal}Table.GetRootAs{table_pascal}Table(_bb);")
    w("        int count = root.ItemsLength;")
    w("")
    w(f"        _mainIndex = new Dictionary<{pk_cs_type}, int>(count);")
    for sf in string_fields:
        w(f"        _str_{sf.name} = new string[count];")
    w("")
    w("        for (int i = 0; i < count; i++)")
    w("        {")
    w(f"            var row = root.Items(i).Value;")

    pk_accessor = pk.name
    w(f"            _mainIndex[row.{pk_accessor}] = i;")

    for sf in string_fields:
        sf_accessor = sf.name
        w(f"            _str_{sf.name}[i] = row.{sf_accessor};")

    w("        }")

    # ---- i18n bundle ----
    if schema.has_i18n:
        w("")
        w("        // ---- i18n bundle ----")
        w("        byte[] i18nBytes = GDNative.GetI18nBytes();")
        w("        if (i18nBytes != null && i18nBytes.Length > 0)")
        w("        {")
        w("            var i18nBundleBb = new ByteBuffer(i18nBytes);")
        w(f'            _i18nBb = _FindTableBytes(i18nBundleBb, "{schema.table}_i18n");')
        w(f"            var i18nRoot = {table_pascal}I18nTable.GetRootAs{table_pascal}I18nTable(_i18nBb);")
        w("            int i18nCount = i18nRoot.EntriesLength;")
        w("")
        w(f"            _i18nIndex = new Dictionary<{pk_cs_type}, int>(i18nCount);")
        for sf in model.i18n_fields:
            w(f"            _i18nStr_{sf.name} = new string[i18nCount];")
        w("")
        w("            for (int j = 0; j < i18nCount; j++)")
        w("            {")
        w(f"                var entry = i18nRoot.Entries(j).Value;")
        w(f"                _i18nIndex[entry.{pk_accessor}] = j;")
        for sf in model.i18n_fields:
            sf_accessor = sf.name
            w(f"                _i18nStr_{sf.name}[j] = entry.{sf_accessor};")
        w("            }")
        w("        }")

    w("    }")
    w("")

    # -- _EnsureLoaded --------------------------------------------------------
    w("    private static void _EnsureLoaded()")
    w("    {")
    w("        if (_mainIndex == null)")
    w('            throw new InvalidOperationException(')
    w(f'                "{class_name}.Preload() must be called before accessing data.");')
    w("    }")
    w("")

    # -- _GetRowIndex ---------------------------------------------------------
    w(f"    private static int _GetRowIndex({pk_cs_type} id)")
    w("    {")
    w("        _EnsureLoaded();")
    w("        if (!_mainIndex.TryGetValue(id, out int idx))")
    w(f'            throw new KeyNotFoundException($"{class_name}: id {{id}} not found.");')
    w("        return idx;")
    w("    }")
    w("")

    # -- per-field accessors --------------------------------------------------
    for field in client_fields:
        _emit_field_accessor(w, schema, field, table_pascal, pk_cs_type)

    # close class
    w("}")
    w("")

    out_path = output_dir / f"{table_pascal}Accessor.cs"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return out_path


def _emit_field_accessor(
    w,
    schema: TableSchema,
    field: FieldDef,
    table_pascal: str,
    pk_cs_type: str,
) -> None:
    """Emit a ``Get{FieldName}(id)`` static method for *field*."""
    method_name = f"Get{field.name}"
    ret_type = _cs_return_type(field)

    w(f"    public static {ret_type} {method_name}({pk_cs_type} id)")
    w("    {")
    w("        int idx = _GetRowIndex(id);")

    if field.type == "string":
        # String fields: return from pre-materialized array
        if field.i18n and schema.has_i18n:
            w("        // i18n: check i18n array first, fallback to main")
            w(f"        if (_i18nIndex != null && _i18nIndex.TryGetValue(id, out int i18nIdx))")
            w("        {")
            w(f"            string i18nVal = _i18nStr_{field.name}[i18nIdx];")
            w("            if (i18nVal != null)")
            w("                return i18nVal;")
            w("        }")
        w(f"        return _str_{field.name}[idx];")

    elif field.type in ("int32", "int64", "float", "double", "bool"):
        # Scalar fields: read from ByteBuffer via FlatBuffers row accessor
        accessor = field.name
        w(f"        var root = {table_pascal}Table.GetRootAs{table_pascal}Table(_bb);")
        w(f"        return root.Items(idx).Value.{accessor};")

    elif field.type == "enum":
        # Enum: return byte value via FlatBuffers row accessor
        accessor = field.name
        w(f"        var root = {table_pascal}Table.GetRootAs{table_pascal}Table(_bb);")
        w(f"        return (byte)root.Items(idx).Value.{accessor};")

    elif field.type == "struct":
        accessor = field.name
        w(f"        var root = {table_pascal}Table.GetRootAs{table_pascal}Table(_bb);")
        w(f"        return root.Items(idx).Value.{accessor}.Value;")

    elif field.type == "array":
        accessor = field.name
        elem_cs = _CS_TYPE_MAP.get(field.element or "", "int")
        if field.element == "enum":
            elem_cs = "byte"
        w(f"        var root = {table_pascal}Table.GetRootAs{table_pascal}Table(_bb);")
        w(f"        var row = root.Items(idx).Value;")
        w(f"        int len = row.{accessor}Length;")
        w(f"        var arr = new {elem_cs}[len];")
        w("        for (int i = 0; i < len; i++)")
        if field.element == "enum":
            w(f"            arr[i] = (byte)row.{accessor}(i);")
        else:
            w(f"            arr[i] = row.{accessor}(i);")
        w("        return arr;")

    w("    }")
    w("")
