"""Task 8.9 -- Generate {table}_accessor.lua files for each config table.

The generated Lua module provides accessor functions that read FlatBuffers
data for scalars and return cached strings from tables built during
``M.preload()``.
"""

from __future__ import annotations

from pathlib import Path

from ct.schema.models import FieldDef, TableSchema


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


# FlatBuffers Lua API read method name per schema type
_LUA_FB_READ: dict[str, str] = {
    "int32": "Int32",
    "int64": "Int64",
    "float": "Float32",
    "double": "Float64",
    "bool":  "Bool",
    "enum":  "Int8",
}


def _field_slot_index(schema: TableSchema, field: FieldDef) -> int:
    """Return the vtable slot index of *field* among non-server_only fields."""
    idx = 0
    for f in schema.fields:
        if f.server_only:
            continue
        if f.name == field.name:
            return idx
        idx += 1
    raise ValueError(f"Field {field.name} not found in schema {schema.table}")


def _i18n_field_slot_index(schema: TableSchema, field: FieldDef) -> int:
    """Slot index inside the I18nEntry (slot 0 = pk, then i18n fields)."""
    idx = 1
    for f in schema.i18n_fields:
        if f.name == field.name:
            return idx
        idx += 1
    raise ValueError(f"i18n field {field.name} not found")


def generate_lua_accessor(schema: TableSchema, output_dir: Path) -> Path:
    """Generate ``{table}_accessor.lua`` and write it to *output_dir*.

    Returns the path of the generated file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    table_pascal = _pascal_case(schema.table)
    client_fields: list[FieldDef] = [f for f in schema.fields if not f.server_only]
    pk = schema.primary_field
    string_fields = [f for f in client_fields if f.type == "string"]

    lines: list[str] = []
    w = lines.append

    # -- header ---------------------------------------------------------------
    w(f"-- Auto-generated by ct/export/lua_accessor_generator.py  DO NOT EDIT")
    w(f"-- Accessor for table: {schema.table}")
    w("")
    w('local flatbuffers = require("flatbuffers")')
    w("")
    w("local M = {}")
    w("")

    # -- private state --------------------------------------------------------
    w("local _loaded = false")
    w("local _main_buf = nil")
    w("local _main_root = nil")
    w("local _main_index = {}  -- id -> row index (0-based)")
    w("local _main_count = 0")
    if string_fields:
        w("local _main_strings = {}  -- [row_index] = { field = value }")
    if schema.has_i18n:
        w("local _i18n_buf = nil")
        w("local _i18n_root = nil")
        w("local _i18n_index = {}  -- id -> entry index (0-based)")
        w("local _i18n_count = 0")
        i18n_str_fields = schema.i18n_fields
        if i18n_str_fields:
            w("local _i18n_strings = {}  -- [entry_index] = { field = value }")
    w("")

    # -- helper: ensure loaded ------------------------------------------------
    w("local function _ensure_loaded()")
    w("    if not _loaded then")
    w(f'        error("{table_pascal}Accessor: preload() must be called before accessing data.")')
    w("    end")
    w("end")
    w("")

    # -- preload --------------------------------------------------------------
    w("function M.preload()")
    w("    -- main bundle")
    w("    local main_bytes = GD.GetMainBytes()")
    w("    _main_buf = flatbuffers.binaryArray.New(main_bytes)")
    w(f"    _main_root = {table_pascal}Table.GetRootAs{table_pascal}Table(_main_buf, 0)")
    w("    _main_count = _main_root:ItemsLength()")
    w("")
    w("    _main_index = {}")
    if string_fields:
        w("    _main_strings = {}")
    w("")
    w("    for i = 0, _main_count - 1 do")
    w("        local row = _main_root:Items(i)")

    pk_getter = _pascal_case(pk.name)
    w(f"        local pk = row:{pk_getter}()")
    w("        _main_index[pk] = i")

    if string_fields:
        w("        _main_strings[i] = {}")
        for sf in string_fields:
            sf_getter = _pascal_case(sf.name)
            w(f'        _main_strings[i]["{sf.name}"] = row:{sf_getter}()')

    w("    end")

    # ---- i18n ----
    if schema.has_i18n:
        w("")
        w("    -- i18n bundle")
        w("    local i18n_bytes = GD.GetI18nBytes()")
        w("    if i18n_bytes and #i18n_bytes > 0 then")
        w("        _i18n_buf = flatbuffers.binaryArray.New(i18n_bytes)")
        w(f"        _i18n_root = {table_pascal}I18nTable.GetRootAs{table_pascal}I18nTable(_i18n_buf, 0)")
        w("        _i18n_count = _i18n_root:EntriesLength()")
        w("")
        w("        _i18n_index = {}")
        if i18n_str_fields:
            w("        _i18n_strings = {}")
        w("")
        w("        for j = 0, _i18n_count - 1 do")
        w("            local entry = _i18n_root:Entries(j)")
        w(f"            local pk = entry:{pk_getter}()")
        w("            _i18n_index[pk] = j")
        if i18n_str_fields:
            w("            _i18n_strings[j] = {}")
            for sf in i18n_str_fields:
                sf_getter = _pascal_case(sf.name)
                w(f'            _i18n_strings[j]["{sf.name}"] = entry:{sf_getter}()')
        w("        end")
        w("    end")

    w("")
    w("    _loaded = true")
    w("end")
    w("")

    # -- per-field accessors --------------------------------------------------
    for field in client_fields:
        _emit_lua_field_accessor(w, schema, field, table_pascal, pk)

    # -- module return --------------------------------------------------------
    w("return M")
    w("")

    out_path = output_dir / f"{schema.table}_accessor.lua"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return out_path


def _emit_lua_field_accessor(
    w,
    schema: TableSchema,
    field: FieldDef,
    table_pascal: str,
    pk: FieldDef,
) -> None:
    """Emit ``M.get_{field_name}(id)`` for *field*."""
    func_name = f"get_{field.name}"
    accessor = _pascal_case(field.name)

    w(f"function M.{func_name}(id)")
    w("    _ensure_loaded()")
    w("    local idx = _main_index[id]")
    w("    if idx == nil then")
    w(f'        error("{table_pascal}Accessor: id " .. tostring(id) .. " not found.")')
    w("    end")

    if field.type == "string":
        if field.i18n and schema.has_i18n:
            w("    -- i18n: check i18n strings first, fallback to main")
            w("    if _i18n_index then")
            w("        local i18n_idx = _i18n_index[id]")
            w("        if i18n_idx ~= nil then")
            w(f'            local val = _i18n_strings[i18n_idx]["{field.name}"]')
            w("            if val ~= nil then")
            w("                return val")
            w("            end")
            w("        end")
            w("    end")
        w(f'    return _main_strings[idx]["{field.name}"]')

    elif field.type in ("int32", "int64", "float", "double", "bool"):
        w(f"    local row = _main_root:Items(idx)")
        w(f"    return row:{accessor}()")

    elif field.type == "enum":
        w(f"    local row = _main_root:Items(idx)")
        w(f"    return row:{accessor}()")

    elif field.type == "struct":
        w(f"    local row = _main_root:Items(idx)")
        w(f"    return row:{accessor}()")

    elif field.type == "array":
        w(f"    local row = _main_root:Items(idx)")
        w(f"    local len = row:{accessor}Length()")
        w("    local arr = {}")
        w("    for i = 0, len - 1 do")
        w(f"        arr[i + 1] = row:{accessor}(i)")
        w("    end")
        w("    return arr")

    w("end")
    w("")
