"""Task 8.9 -- Generate {table}_accessor.lua files for each config table.

The generated Lua module provides ``M.ByID(id)`` returning a RowMeta table with
``__index`` that lazily reads fields from i18n cache -> main cache -> FlatBuffers.

Field access uses PascalCase (matching flatc output), e.g. ``row.RequiredLevel``.
"""

from __future__ import annotations

from pathlib import Path

from ct.schema.models import FieldDef, TableSchema


def generate_lua_accessor(schema: TableSchema, output_dir: Path) -> Path:
    """Generate ``{table}_accessor.lua`` and write it to *output_dir*.

    Returns the path of the generated file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    table_pascal = schema.table
    client_fields: list[FieldDef] = [f for f in schema.fields if not f.server_only]
    pk = schema.primary_field
    string_fields = [f for f in client_fields if f.type == "string"]
    i18n_str_fields = schema.i18n_fields if schema.has_i18n else []

    lines: list[str] = []
    w = lines.append

    # -- header ---------------------------------------------------------------
    w(f"-- Auto-generated by ct/export/lua_accessor_generator.py  DO NOT EDIT")
    w(f"-- Accessor for table: {schema.table}")
    w(f"--")
    w(f"-- Usage: local row = Config.{table_pascal}.ByID(id)")
    w(f"-- Fields:")
    for f in client_fields:
        flags = []
        if f.i18n:
            flags.append("i18n")
        flag_str = f", {', '.join(flags)}" if flags else ""
        pascal = f.name
        w(f"--   .{pascal} ({f.type}{flag_str})")
    w("")
    w('local flatbuffers = require("flatbuffers")')

    # FlatBuffers types as local require (not global)
    fb_types = {f"{table_pascal}Table", "DataBundle"}
    if schema.has_i18n:
        fb_types.add(f"{table_pascal}I18nTable")
    for t in sorted(fb_types):
        w(f'local {t} = require("{t}")')
    w("")
    w("local M = {}")
    w("")

    # -- private state --------------------------------------------------------
    w("local _loaded = false")
    w("local _main_root = nil")
    w("local _main_index = {}  -- id -> row index (1-based)")
    if schema.has_i18n:
        w("local _i18n_strings = {}  -- [id] = { field = value }")
    w("")

    # -- helper: extract table bytes from DataBundle --------------------------
    w("local function _FindTableBytes(bundle_bb, table_name)")
    w("    local bundle = DataBundle.GetRootAsDataBundle(bundle_bb, 0)")
    w("    local count = bundle:TablesLength()")
    w("    for i = 1, count do")
    w("        local bt = bundle:Tables(i)")
    w("        if bt:Name() == table_name then")
    w("            return flatbuffers.binaryArray.New(bt:DataAsString(1, bt:DataLength()))")
    w("        end")
    w("    end")
    w("    error(\"Table '\" .. table_name .. \"' not found in config bundle.\")")
    w("end")
    w("")

    # -- i18n indexing --------------------------------------------------------
    if schema.has_i18n:
        w("local function _index_i18n()")
        w("    local i18n_bytes = GD.GetI18nBytes()")
        w("    if not i18n_bytes or #i18n_bytes == 0 then")
        w("        _i18n_strings = {}")
        w("        return")
        w("    end")
        w("")
        w("    local i18n_bb = flatbuffers.binaryArray.New(i18n_bytes)")
        w(f'    local i18n_buf = _FindTableBytes(i18n_bb, "{schema.table}_i18n")')
        w(f"    local i18n_root = {table_pascal}I18nTable.GetRootAs{table_pascal}I18nTable(i18n_buf, 0)")
        w("    local i18n_count = i18n_root:EntriesLength()")
        w("")
        w("    _i18n_strings = {}")
        w("    for j = 1, i18n_count do")
        w("        local entry = i18n_root:Entries(j)")
        pk_getter = pk.name
        w(f"        local pk = entry:{pk_getter}()")
        w("        _i18n_strings[pk] = {}")
        for sf in i18n_str_fields:
            sf_getter = sf.name
            w(f'        _i18n_strings[pk]["{sf_getter}"] = entry:{sf_getter}()')
        w("    end")
        w("end")
        w("")

    # -- helper: get i18n string for a row index and field key ----------------
    if schema.has_i18n:
        w("local function _get_i18n_string(idx, key)")
        w("    local row = _main_root:Items(idx)")
        pk_getter = pk.name
        w(f"    local id = row:{pk_getter}()")
        w("    if _i18n_strings[id] and _i18n_strings[id][key] ~= nil then")
        w("        return _i18n_strings[id][key]")
        w("    end")
        w("    return nil")
        w("end")
        w("")

    # -- preload --------------------------------------------------------------
    w("function M.preload()")
    w("    -- main bundle")
    w("    local main_bytes = GD.GetMainBytes()")
    w("    local bundle_bb = flatbuffers.binaryArray.New(main_bytes)")
    w(f'    local main_buf = _FindTableBytes(bundle_bb, "{schema.table}")')
    w(f"    _main_root = {table_pascal}Table.GetRootAs{table_pascal}Table(main_buf, 0)")
    w("    local main_count = _main_root:ItemsLength()")
    w("")
    w("    _main_index = {}")
    w("")
    w("    for i = 1, main_count do")
    w("        local row = _main_root:Items(i)")
    pk_getter = pk.name
    w(f"        local pk = row:{pk_getter}()")
    w("        _main_index[pk] = i")
    w("    end")
    w("")

    if schema.has_i18n:
        w("    -- i18n bundle (reload-safe)")
        w("    _index_i18n()")
        w("")

    w("    _loaded = true")
    w("end")
    w("")

    # -- RowMeta (must be defined before ByID) -------------------------------
    w("local RowMeta = {}")
    w("")

    # -- ByID ----------------------------------------------------------------
    w("function M.ByID(id)")
    w("    if not _loaded then M.preload() end")
    w("    local idx = _main_index[id]")
    w("    if not idx then return nil end")
    w("    return setmetatable({ _idx = idx }, RowMeta)")
    w("end")
    w("")
    w("function RowMeta:__index(key)")
    w("    local idx = rawget(self, \"_idx\")")
    w("")
    if schema.has_i18n:
        w("    local i18n_val = _get_i18n_string(idx, key)")
        w("    if i18n_val ~= nil then return i18n_val end")
        w("")
    w("    -- key is PascalCase, matches flatc method name directly")
    w("    local row = _main_root:Items(idx)")
    w("    local method = row[key]")
    w("    if type(method) == \"function\" then")
    w("        return method(row)")
    w("    end")
    w("")
    w("    return nil")
    w("end")
    w("")

    # -- module return --------------------------------------------------------
    w("return M")
    w("")

    out_path = output_dir / f"{table_pascal}Accessor.lua"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return out_path
