/*
 * gd_native.cpp
 *
 * Hand-written reference implementation for the GD native loading API.
 * This file is NOT generated by the ct export tool. It is provided as a
 * starting point for integrating GD binary bundles into a C/C++ runtime
 * (e.g. a Unity native plugin, Unreal module, or standalone game engine).
 *
 * This is reference code intended for clarity, not production use.
 * A production implementation should add:
 *   - Thread safety (mutex around load/unload)
 *   - Error reporting via callback or return codes
 *   - Memory-mapped file I/O for large bundles
 *   - Async loading support
 */

#include "gd_native.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

/* ---------------------------------------------------------------------------
 * Internal state
 * --------------------------------------------------------------------------- */

struct GD_Buffer {
    void*  data;
    size_t size;
};

static GD_Buffer g_main_buffer = { nullptr, 0 };
static GD_Buffer g_i18n_buffer = { nullptr, 0 };

/* ---------------------------------------------------------------------------
 * Helper: read an entire file into a heap-allocated buffer
 * --------------------------------------------------------------------------- */

static bool read_file(const char* path, GD_Buffer* out) {
    if (!path || !out) {
        return false;
    }

    FILE* fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "[GD] Failed to open file: %s\n", path);
        return false;
    }

    /* Determine file size */
    fseek(fp, 0, SEEK_END);
    long file_size = ftell(fp);
    fseek(fp, 0, SEEK_SET);

    if (file_size <= 0) {
        fprintf(stderr, "[GD] File is empty or unreadable: %s\n", path);
        fclose(fp);
        return false;
    }

    /* Allocate buffer and read contents */
    void* buffer = malloc(static_cast<size_t>(file_size));
    if (!buffer) {
        fprintf(stderr, "[GD] Failed to allocate %ld bytes for: %s\n",
                file_size, path);
        fclose(fp);
        return false;
    }

    size_t bytes_read = fread(buffer, 1, static_cast<size_t>(file_size), fp);
    fclose(fp);

    if (bytes_read != static_cast<size_t>(file_size)) {
        fprintf(stderr, "[GD] Incomplete read for: %s (got %zu of %ld bytes)\n",
                path, bytes_read, file_size);
        free(buffer);
        return false;
    }

    out->data = buffer;
    out->size = static_cast<size_t>(file_size);
    return true;
}

/* ---------------------------------------------------------------------------
 * Helper: free a buffer
 * --------------------------------------------------------------------------- */

static void free_buffer(GD_Buffer* buf) {
    if (buf->data) {
        free(buf->data);
        buf->data = nullptr;
        buf->size = 0;
    }
}

/* ---------------------------------------------------------------------------
 * Public API implementation
 * --------------------------------------------------------------------------- */

void GD_Load(const char* main_path, const char* i18n_path) {
    /* Unload any previously loaded data first */
    GD_Unload();

    /* Load main bundle (required) */
    if (!main_path) {
        fprintf(stderr, "[GD] GD_Load: main_path must not be NULL\n");
        return;
    }

    if (!read_file(main_path, &g_main_buffer)) {
        fprintf(stderr, "[GD] GD_Load: failed to load main bundle\n");
        return;
    }

    fprintf(stderr, "[GD] Loaded main bundle: %zu bytes from %s\n",
            g_main_buffer.size, main_path);

    /* Load i18n bundle (optional) */
    if (i18n_path) {
        if (read_file(i18n_path, &g_i18n_buffer)) {
            fprintf(stderr, "[GD] Loaded i18n bundle: %zu bytes from %s\n",
                    g_i18n_buffer.size, i18n_path);
        } else {
            fprintf(stderr, "[GD] Warning: failed to load i18n bundle, "
                    "continuing without it\n");
        }
    }
}

const void* GD_GetMainBytes(size_t* out_size) {
    if (out_size) {
        *out_size = g_main_buffer.size;
    }
    return g_main_buffer.data;
}

const void* GD_GetI18nBytes(size_t* out_size) {
    if (out_size) {
        *out_size = g_i18n_buffer.size;
    }
    return g_i18n_buffer.data;
}

void GD_Unload() {
    free_buffer(&g_main_buffer);
    free_buffer(&g_i18n_buffer);
}
