/*
 * gd_xlua_register.cpp
 *
 * Hand-written reference implementation for registering the GD native API
 * with xLua. This file is NOT generated by the ct export tool.
 *
 * This registers the following Lua functions in the "GD" table:
 *   GD.Load(main_path, i18n_path)   -- load binary bundles from disk
 *   GD.GetMainBytes()               -- returns userdata + size
 *   GD.GetI18nBytes()               -- returns userdata + size
 *   GD.Unload()                     -- free loaded data
 *
 * Lua usage example:
 *   GD.Load("data_zh.bin", "data_en.bin")
 *   local main_data, main_size = GD.GetMainBytes()
 *   -- pass main_data to FlatBuffers for parsing
 *   GD.Unload()
 *
 * Integration:
 *   In your xLua initialization code, call GD_XLua_Open(L) after
 *   creating the Lua state. This is typically done in the same place
 *   where you register other native modules.
 *
 * Build notes:
 *   - Link against gd_native.cpp (provides GD_Load, etc.)
 *   - Include xLua headers (lua.h, lauxlib.h, lualib.h)
 *   - Compile as part of your xLua native plugin
 */

#include "gd_native.h"

extern "C" {
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
}

/* ---------------------------------------------------------------------------
 * Lua wrapper: GD.Load(main_path, i18n_path)
 *
 * Arguments:
 *   main_path (string)          - path to the main binary bundle (required)
 *   i18n_path (string or nil)   - path to the i18n binary bundle (optional)
 *
 * Returns: nothing
 * --------------------------------------------------------------------------- */

static int l_gd_load(lua_State* L) {
    const char* main_path = luaL_checkstring(L, 1);
    const char* i18n_path = lua_isstring(L, 2) ? lua_tostring(L, 2) : nullptr;

    GD_Load(main_path, i18n_path);

    return 0;  /* no return values */
}

/* ---------------------------------------------------------------------------
 * Lua wrapper: GD.GetMainBytes()
 *
 * Returns:
 *   userdata  - light userdata pointing to the raw bytes (or nil if not loaded)
 *   number    - size of the data in bytes (or 0)
 *
 * The returned userdata is a pointer to the FlatBuffers data. It can be
 * passed to a FlatBuffers Lua binding for parsing. The pointer remains
 * valid until GD.Unload() is called.
 * --------------------------------------------------------------------------- */

static int l_gd_get_main_bytes(lua_State* L) {
    size_t size = 0;
    const void* data = GD_GetMainBytes(&size);

    if (data && size > 0) {
        lua_pushlightuserdata(L, const_cast<void*>(data));
        lua_pushinteger(L, static_cast<lua_Integer>(size));
        return 2;  /* userdata, size */
    }

    lua_pushnil(L);
    lua_pushinteger(L, 0);
    return 2;  /* nil, 0 */
}

/* ---------------------------------------------------------------------------
 * Lua wrapper: GD.GetI18nBytes()
 *
 * Returns:
 *   userdata  - light userdata pointing to the raw bytes (or nil if not loaded)
 *   number    - size of the data in bytes (or 0)
 * --------------------------------------------------------------------------- */

static int l_gd_get_i18n_bytes(lua_State* L) {
    size_t size = 0;
    const void* data = GD_GetI18nBytes(&size);

    if (data && size > 0) {
        lua_pushlightuserdata(L, const_cast<void*>(data));
        lua_pushinteger(L, static_cast<lua_Integer>(size));
        return 2;  /* userdata, size */
    }

    lua_pushnil(L);
    lua_pushinteger(L, 0);
    return 2;  /* nil, 0 */
}

/* ---------------------------------------------------------------------------
 * Lua wrapper: GD.Unload()
 *
 * Returns: nothing
 * --------------------------------------------------------------------------- */

static int l_gd_unload(lua_State* L) {
    (void)L;  /* unused */
    GD_Unload();
    return 0;
}

/* ---------------------------------------------------------------------------
 * Registration table
 * --------------------------------------------------------------------------- */

static const luaL_Reg gd_funcs[] = {
    { "Load",         l_gd_load           },
    { "GetMainBytes", l_gd_get_main_bytes },
    { "GetI18nBytes", l_gd_get_i18n_bytes },
    { "Unload",       l_gd_unload         },
    { nullptr,        nullptr             },
};

/* ---------------------------------------------------------------------------
 * Public: open the GD module in a Lua state
 *
 * Call this once during xLua initialization:
 *   GD_XLua_Open(L);
 *
 * After this call, Lua code can use:
 *   GD.Load("data_zh.bin", "data_en.bin")
 *   local data, size = GD.GetMainBytes()
 *   GD.Unload()
 * --------------------------------------------------------------------------- */

extern "C" int GD_XLua_Open(lua_State* L) {
    luaL_newlib(L, gd_funcs);
    lua_setglobal(L, "GD");
    return 0;
}
