//! Deterministic S/M/L benchmark workspaces. All inputs are generated by Rust.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use ct_app::workspace::Workspace;
use ct_domain::hashing::{compute_schema_hash, python_json_pretty};
use ct_domain::repository::Resource;
use ct_excel::layout::{build_layout, Column};
use ct_excel::manifest::LayoutManifest;
use ct_excel::migrate::CellValue;
use ct_excel::template::build_template_with_rows;
use serde_json::{json, Map, Value};

const SEED: u64 = 20260918;
const SIZES: &[(&str, usize, usize)] = &[("s", 10, 100), ("m", 50, 2_000), ("l", 100, 10_000)];
const REAL_SIZES: &[&str] = &["r", "r-full"];
const LANGS: &[&str] = &["en", "ja"];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

pub fn generate(sizes: &[String], out: Option<PathBuf>) -> Result<()> {
    let out_dir = match out {
        Some(path) if path.is_absolute() => path,
        Some(path) => repo_root().join(path),
        None => repo_root().join("native/target/bench"),
    };
    let wanted: Vec<&str> = if sizes.is_empty() {
        vec!["s", "m", "l"]
    } else {
        sizes.iter().map(String::as_str).collect()
    };
    let all = wanted.contains(&"all");
    for size in &wanted {
        if !SIZES.iter().any(|(name, _, _)| name == size)
            && !REAL_SIZES.contains(size)
            && *size != "all"
        {
            bail!("未知尺寸 {size}（可选 s/m/l/r/r-full 或 all = s,m,l）");
        }
    }
    for &(size, tables, rows) in SIZES {
        if all || wanted.contains(&size) {
            generate_small(size, tables, rows, &out_dir)?;
        }
    }
    let real: Vec<String> = wanted
        .iter()
        .filter(|size| REAL_SIZES.contains(size))
        .map(|size| (*size).to_string())
        .collect();
    if !real.is_empty() {
        crate::real_fixture::generate(&real, Some(out_dir))?;
    }
    Ok(())
}

fn write(root: &Path, relative: &str, content: &str) -> Result<()> {
    let path = root.join(relative);
    std::fs::create_dir_all(path.parent().context("文件没有父目录")?)?;
    std::fs::write(path, content)?;
    Ok(())
}

fn config(root: &Path, tables: usize) -> Result<()> {
    write(
        root,
        "config/global.yaml",
        "primary_lang: zh\nsecondary_langs:\n  - en\n  - ja\n",
    )?;
    for (file, body) in [
        ("rarity", "kind: enum\nname: Rarity\nvalues:\n  - name: Common\n  - name: Rare\n  - name: Epic\n  - name: Legend\n  - name: Mythic\n"),
        ("kind", "kind: enum\nname: Kind\nvalues:\n  - name: None\n  - name: Active\n  - name: Passive\n  - name: Hidden\n"),
        ("drop_rule", "kind: record\nname: DropRule\nfields:\n  - name: Min\n    type: int32\n  - name: Max\n    type: int32\n"),
    ] {
        write(root, &format!("config/types/{file}.yaml"), body)?;
    }
    let fields = [
        ("Id", "int32"),
        ("CodeName", "string"),
        ("Name", "string"),
        ("Desc", "string"),
        ("Tag", "string"),
        ("Level", "int32"),
        ("Exp", "int32"),
        ("Cost", "int32"),
        ("Weight", "int32"),
        ("Big", "int64"),
        ("Huge", "uint64"),
        ("Small", "int16"),
        ("Flag", "bool"),
        ("Rate", "float"),
        ("Ratio", "double"),
        ("Quality", "Rarity"),
        ("Mode", "Kind"),
        ("Owner", "int32"),
        ("Score", "int32"),
    ];
    for index in 0..tables {
        let name = table_name(index);
        let mut text = format!("table: {name}\nprimary: Id\nfields:\n");
        for (field, kind) in fields {
            text.push_str(&format!("  - name: {field}\n    type: {kind}\n"));
            if matches!(field, "Name" | "Desc") {
                text.push_str("    i18n: true\n");
            }
            if field == "Owner" && index > 0 {
                text.push_str("    ref: Base.Id\n");
            }
        }
        if index % 2 == 0 {
            text.push_str("  - name: Note\n    type: string\n");
        } else {
            text.push_str("  - name: Drops\n    type: vector<DropRule>\n    excel_columns: 2\n");
            text.push_str("  - name: Chain\n    type: vector<int32>\n    excel_columns: 3\n");
        }
        text.push_str("indexes:\n  - kind: codename\n");
        write(
            root,
            &format!("config/schemas/{}.yaml", name.to_lowercase()),
            &text,
        )?;
    }
    Ok(())
}

fn table_name(index: usize) -> String {
    if index == 0 {
        "Base".into()
    } else {
        format!("T{index:03}")
    }
}

fn splitmix64(mut state: u64) -> u64 {
    state = state.wrapping_add(0x9E3779B97F4A7C15);
    let mut z = state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
    z ^ (z >> 31)
}

fn cell(table: &str, odd: bool, row: usize, column: &Column, mutate: bool) -> Option<CellValue> {
    let leaf = column.leaf.as_str();
    if column.stable_path.contains("/Drops") || column.stable_path.contains("/Chain") {
        return None;
    }
    let key = splitmix64(
        SEED ^ ((row as u64) << 32)
            ^ ((column.index as u64) << 16)
            ^ table.bytes().fold(0u64, |hash, byte| {
                hash.wrapping_mul(31).wrapping_add(byte as u64)
            }),
    );
    if odd
        && !matches!(leaf, "Id" | "CodeName")
        && !(mutate && row == 1 && leaf == "Tag")
        && key % 1_000 < 120
    {
        return None;
    }
    Some(match leaf {
        "Id" => CellValue::Number(row as f64),
        "Owner" => CellValue::Number((row % 100 + 1) as f64),
        "CodeName" => CellValue::Text(format!("{table}_{row}")),
        "Tag" if mutate && row == 1 => CellValue::Text("bench-mutation".into()),
        "Flag" => CellValue::Bool(row % 2 != 0),
        "Quality" => CellValue::Text(
            ["Common", "Rare", "Epic", "Legend", "Mythic"][(key % 5) as usize].into(),
        ),
        "Mode" => {
            CellValue::Text(["None", "Active", "Passive", "Hidden"][(key % 4) as usize].into())
        }
        _ => match column.type_text.as_str() {
            "string" => CellValue::Text(format!("{leaf}{row}")),
            "int16" => CellValue::Number((key % 32_000) as f64),
            "int32" | "int64" | "uint64" => CellValue::Number((key % 100_000) as f64),
            "float" | "double" => CellValue::Number(((key % 10_000) as f64) / 10_000.0),
            _ => CellValue::Text(format!("{leaf}{row}")),
        },
    })
}

fn rows(
    table: &str,
    odd: bool,
    count: usize,
    columns: &[Column],
    mutate: bool,
) -> (Vec<Vec<Option<CellValue>>>, u64) {
    let mut result = Vec::with_capacity(count);
    let mut written = 0;
    for row in 1..=count {
        let values: Vec<_> = columns
            .iter()
            .map(|column| cell(table, odd, row, column, mutate))
            .collect();
        written += values.iter().filter(|cell| cell.is_some()).count() as u64;
        result.push(values);
    }
    (result, written)
}

fn translate(root: &Path) -> Result<u64> {
    let mut written = 0;
    for lang in LANGS {
        for entry in std::fs::read_dir(root.join("i18n").join(lang))? {
            let path = entry?.path();
            if path.extension().is_none_or(|ext| ext != "json") {
                continue;
            }
            let mut payload: Map<String, Value> = serde_json::from_slice(&std::fs::read(&path)?)?;
            for value in payload.values_mut() {
                let Some(item) = value.as_object_mut() else {
                    continue;
                };
                let source = item
                    .get("source")
                    .and_then(Value::as_str)
                    .unwrap_or("")
                    .to_string();
                item.insert("text".into(), Value::String(format!("[{lang}] {source}")));
                item.insert("confirmed".into(), Value::Bool(true));
                item.insert("status".into(), Value::String("confirmed".into()));
                written += 1;
            }
            std::fs::write(&path, serde_json::to_string_pretty(&payload)? + "\n")?;
        }
    }
    Ok(written)
}

fn mutate_translation(root: &Path, target: &str) -> Result<Value> {
    let path = root.join(format!("i18n/en/{target}.json"));
    let mut payload: Map<String, Value> = serde_json::from_slice(&std::fs::read(path)?)?;
    let (_, first) = payload.iter_mut().next().context("译文骨架没有条目")?;
    let item = first.as_object_mut().context("译文条目格式错误")?;
    let current = item
        .get("text")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    item.insert("text".into(), Value::String(format!("{current}!")));
    item.insert("confirmed".into(), Value::Bool(false));
    item.insert("status".into(), Value::String("pending".into()));
    write(
        root,
        &format!("mutations/{target}.json"),
        &(serde_json::to_string_pretty(&payload)? + "\n"),
    )?;
    let meta = json!({"table": target, "tableSource": format!("excel/{target}.xlsx"), "i18nLang": "en", "i18nTarget": format!("i18n/en/{target}.json")});
    write(
        root,
        "mutations/mutations.json",
        &(serde_json::to_string_pretty(&meta)? + "\n"),
    )?;
    Ok(meta)
}

fn generate_small(size: &str, tables: usize, row_count: usize, out_dir: &Path) -> Result<()> {
    let root = out_dir.join(format!("bench-{size}"));
    if root.exists() {
        std::fs::remove_dir_all(&root)
            .with_context(|| format!("清理旧夹具失败：{}", root.display()))?;
    }
    std::fs::create_dir_all(&root)?;
    config(&root, tables)?;
    let ws = Workspace::open(&root).map_err(|e| anyhow::anyhow!("装载夹具工作区失败：{e}"))?;
    let deps: Vec<Resource> = ws
        .resources
        .records
        .iter()
        .cloned()
        .map(Resource::Record)
        .chain(ws.resources.enums.iter().cloned().map(Resource::Enum))
        .collect();
    let records = ws.resources.records_map();
    let enums = crate::real_fixture::enum_map(&ws);
    let mut written = 0;
    for (index, table_name) in (0..tables).map(table_name).enumerate() {
        let table = ws
            .resources
            .tables
            .iter()
            .find(|table| table.table == table_name)
            .with_context(|| format!("工作区缺少表 {table_name}"))?;
        let layout = build_layout(table, &compute_schema_hash(table, &deps), &records);
        let (data, count) = rows(
            &table_name,
            index % 2 == 1,
            row_count,
            &layout.columns,
            false,
        );
        written += count;
        let (bytes, warnings) = build_template_with_rows(&layout, &enums, &table.primary, &data)?;
        for warning in warnings {
            eprintln!("[fixture] {warning}");
        }
        let excel_path = ws.excel_dir().join(table.resolved_excel_file());
        std::fs::create_dir_all(excel_path.parent().context("Excel 路径没有父目录")?)?;
        std::fs::write(excel_path, bytes)?;
        let doc =
            LayoutManifest::from_layout(&layout, &crate::real_fixture::slot_offsets(&ws, table));
        write(
            &root,
            &format!("excel/layout_manifests/{table_name}.json"),
            &(python_json_pretty(&doc.payload()) + "\n"),
        )?;
        if index == 1 {
            let (changed, _) = rows(&table_name, true, row_count, &layout.columns, true);
            let (bytes, _) = build_template_with_rows(&layout, &enums, &table.primary, &changed)?;
            std::fs::create_dir_all(root.join("mutations"))?;
            std::fs::write(root.join(format!("mutations/{table_name}.xlsx")), bytes)?;
        }
    }
    ct_app::i18n::i18n_sync(&ws, None, None).map_err(|e| anyhow::anyhow!("i18n sync 失败：{e}"))?;
    let translated = translate(&root)?;
    let target = if tables > 1 { "T001" } else { "Base" };
    let mutation = mutate_translation(&root, target)?;
    for leftover in ["output", "cache", ".ct"] {
        let path = root.join(leftover);
        if path.exists() {
            std::fs::remove_dir_all(path)?;
        }
    }
    let digest = crate::real_fixture::input_digest(&root)?;
    let summary = json!({
        "schema": "ct-bench-fixture/1", "size": size, "seed": SEED,
        "tables": tables, "rowsPerTable": row_count, "columnsPerTable": 20,
        "dataCells": written, "translatedEntries": translated,
        "languages": ["zh", "en", "ja"],
        "uniform": "偶数表填满、奇数表含 vector<Record>/vector<int32> 且约 12% 单元格留空",
        "mutation": mutation, "inputDigest": digest, "root": root.display().to_string(),
    });
    write(
        &root,
        "FIXTURE.json",
        &(serde_json::to_string_pretty(&summary)? + "\n"),
    )?;
    println!(
        "[fixture] {size}：{tables} 张表 / {written} 个数据单元格 / {}",
        root.display()
    );
    Ok(())
}
