"""Canonical FlatBuffers schema generation for  resources.

All named Records and Enums are emitted once, in deterministic dependency
order, into a single ``types.fbs``; every Table schema ``include``s it and
defines only itself, its index container and the necessary root structures.
Records always generate FlatBuffers ``table``; named Enums use ``byte``.
"""

from __future__ import annotations

from pathlib import Path

from ct.schema.resources import (
    EnumResource,
    RecordResource,
    SchemaResource,
    TableResource,
)
from ct.schema.type_expression import (
    NamedType,
    ScalarType,
    TypeExpression,
    VectorType,
    serialize_type_expression,
)

_FBS_TYPE_MAP = {
    "int32": "int32",
    "int64": "int64",
    "float": "float32",
    "double": "float64",
    "bool": "bool",
    "string": "string",
}


def _fbs_type(type_expr: TypeExpression) -> str:
    if isinstance(type_expr, ScalarType):
        return _FBS_TYPE_MAP[type_expr.name]
    if isinstance(type_expr, NamedType):
        return type_expr.name
    if isinstance(type_expr, VectorType):
        return f"[{_fbs_type(type_expr.element)}]"
    raise TypeError(f"未知 Type Expression 节点: {type_expr}")


def types_fbs_text(
    order: list[str],
    resources: dict[str, SchemaResource],
) -> str:
    """Emit the shared ``types.fbs`` in deterministic dependency order."""
    lines: list[str] = []
    seen: set[str] = set()
    for resource_id in order:
        resource = resources[resource_id]
        if isinstance(resource, EnumResource):
            entries = ", ".join(
                f"{value} = {index}" for index, value in enumerate(resource.values)
            )
            lines.append(f"enum {resource.name} : byte {{ {entries} }}")
            lines.append("")
        elif isinstance(resource, RecordResource):
            lines.append(f"table {resource.name} {{")
            for field in resource.fields:
                lines.append(f"  {field.name}: {_fbs_type(field.type_expr)};")
            lines.append("}")
            lines.append("")
        seen.add(resource_id)
    return "\n".join(lines)


def _table_fbs_text(table: TableResource, order: list[str]) -> str:
    lines: list[str] = []
    lines.append(f"// Auto-generated by ct/export/canonical_fbs.py  DO NOT EDIT")
    lines.append("include \"types.fbs\";")
    lines.append("")
    lines.append(f"table {table.table} {{")
    for field in table.fields:
        if field.server_only:
            continue
        lines.append(f"  {field.name}: {_fbs_type(field.type_expr)};")
    lines.append("}")
    lines.append("")
    if table.primary:
        lines.append("struct IndexEntry {")
        lines.append("  id: int32;")
        lines.append("  row: int32;")
        lines.append("}")
        lines.append("")
    lines.append(f"table {table.table}Table {{")
    lines.append(f"  items: [{table.table}];")
    if table.primary:
        lines.append("  index: [IndexEntry];")
    lines.append("}")
    lines.append("")
    lines.append(f"root_type {table.table}Table;")
    lines.append("")
    return "\n".join(lines)


def table_fbs_text(table: TableResource) -> str:
    return _table_fbs_text(table, [])


def _duplicate_symbols(text: str) -> list[str]:
    """Return duplicated FlatBuffers symbol names declared in *text*."""
    import re

    declarations = re.findall(r"^(?:enum|table|struct)\s+([A-Za-z_][A-Za-z0-9_]*)\b", text, re.M)
    seen: set[str] = set()
    duplicates: list[str] = []
    for name in declarations:
        if name in seen and name not in duplicates:
            duplicates.append(name)
        seen.add(name)
    return sorted(duplicates)


def validate_canonical_fbs(types_text: str, table_texts: dict[str, str], resources: list[SchemaResource]) -> None:
    """Reject duplicate symbols, missing shared types and accidental structs.

    - each named Record/Enum must be declared exactly once (in ``types.fbs``);
    - Records must generate FlatBuffers ``table`` (never ``struct``);
    - ``types.fbs`` must not include anything (no include cycles).
    """
    import re

    declaration = re.compile(r"^(enum|table|struct)\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.M)

    def _declarations(text: str) -> dict[str, str]:
        return {name: kind for kind, name in declaration.findall(text)}

    if "include" in types_text:
        raise ValueError("types.fbs 不得 include 其他文件（不允许 include 环）")

    types_decl = _declarations(types_text)
    duplicates: list[str] = []
    seen: set[str] = set()
    for kind, name in declaration.findall(types_text):
        if name in seen and name not in duplicates:
            duplicates.append(name)
        seen.add(name)
    if duplicates:
        raise ValueError(f"types.fbs 存在重复符号: {', '.join(sorted(duplicates))}")

    for resource in resources:
        if isinstance(resource, EnumResource):
            if types_decl.get(resource.name) != "enum":
                raise ValueError(f"共享 Enum '{resource.name}' 未在 types.fbs 声明为 enum")
        elif isinstance(resource, RecordResource):
            kind = types_decl.get(resource.name)
            if kind != "table":
                raise ValueError(
                    f"共享 Record '{resource.name}' 必须生成 FlatBuffers table，"
                    f"当前为 {kind or '缺失'}"
                )

    # every table schema must not re-declare a shared type (no copied definitions)
    for table_name, table_text in table_texts.items():
        table_decl = _declarations(table_text)
        for name in table_decl:
            if name in types_decl:
                raise ValueError(
                    f"{table_name}.fbs 重复定义了共享类型 '{name}'（应通过 include 引用）"
                )
