"""C# / Lua accessor emitters for the canonical model.

Emit deterministic row accessors plus the table-level Code/Group query APIs.
Both languages expose the same method names and missing/ordering semantics;
the actual binary traversal delegates to the platform reader (WireReader /
GD). This text is a format-contract surface and is verified by golden tests.
"""

from __future__ import annotations

from ct.export.canonical_accessor_model import (
    AccessorField,
    CanonicalAccessorModel,
    build_accessor_model,
)
from ct.schema.indexes import QueryIndex


def _scalar_reader(field: AccessorField) -> str:
    if field.type_text == "int64":
        return "WireReader.I64"
    if field.type_text == "float":
        return "WireReader.F32"
    if field.type_text == "double":
        return "WireReader.F64"
    if field.type_text == "bool":
        return "WireReader.Bool"
    if field.type_text == "string":
        return "WireReader.Str"
    if field.type_text == "int32":
        return "WireReader.I32"
    return "WireReader.I8"  # enum


def _lua_reader(field: AccessorField) -> str:
    if field.type_text == "int64":
        return "GD.I64"
    if field.type_text == "float":
        return "GD.F32"
    if field.type_text == "double":
        return "GD.F64"
    if field.type_text == "bool":
        return "GD.I8(s, {slot}) ~= 0"
    if field.type_text == "string":
        return "GD.Str"
    if field.type_text == "int32":
        return "GD.I32"
    return "GD.I8"  # enum


def generate_csharp_accessor(model: CanonicalAccessorModel) -> str:
    table = model.table.table
    lines: list[str] = []
    lines.append("// <auto-generated/>")
    lines.append(f"// Canonical C# accessor for {table} (v4)")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append(f"public static partial class {table}Accessor")
    lines.append("{")
    lines.append("    private static readonly object _lock = new();")
    for index in model.indexes:
        if index.kind == "code":
            lines.append(f"    /// <summary>Exact-string Code lookup; returns null when missing.</summary>")
            lines.append(f"    public static {table}Row? ByCode(string code)")
            lines.append("    {")
            lines.append(f"        var row = WireReader.LookupCode(TableName, {index.slot}, code);")
            lines.append(f"        return row == -1 ? ({table}Row?)null : new {table}Row(row);")
            lines.append("    }")
        else:
            lines.append(f"    /// <summary>Group lookup; returns zero or more rows in deterministic order.</summary>")
            lines.append(f"    public static IReadOnlyList<{table}Row> ByGroupKey(int value)")
            lines.append("    {")
            lines.append(f"        var rows = WireReader.LookupGroup(TableName, {index.slot}, value);")
            lines.append(f"        var result = new List<{table}Row>(rows.Length);")
            lines.append("        foreach (var row in rows) result.Add(new " + table + "Row(row));")
            lines.append("        return result;")
            lines.append("    }")
    lines.append(f"    private const string TableName = \"{table}\";")
    lines.append("}")
    lines.append("")
    lines.append(f"public readonly struct {table}Row")
    lines.append("{")
    lines.append("    private readonly int _row;")
    lines.append(f"    internal {table}Row(int row) {{ _row = row; }}")
    for field in model.client_fields:
        if field.kind == "vector":
            lines.append(f"    public int {field.name}Count => WireReader.VecLen(TableName, {field.slot}, _row);")
            lines.append(f"    public int {field.name}At(int i) => WireReader.VecI32(TableName, {field.slot}, _row, i);")
        else:
            reader = _scalar_reader(field)
            lines.append(f"    public {_csharp_type(field)} {field.name} => {reader}(TableName, {field.slot}, _row);")
    lines.append("}")
    return "\n".join(lines)


def _csharp_type(field: AccessorField) -> str:
    if field.type_text == "int64":
        return "long"
    if field.type_text == "float":
        return "float"
    if field.type_text == "double":
        return "double"
    if field.type_text == "bool":
        return "bool"
    if field.type_text == "string":
        return "string"
    return "int"  # int32 / enum byte


def generate_lua_accessor(model: CanonicalAccessorModel) -> str:
    table = model.table.table
    lines: list[str] = []
    lines.append(f"-- Auto-generated canonical Lua accessor for {table} (v4)")
    lines.append('local GD = require("gd")')
    lines.append(f"local _tbl = \"{table}\"")
    lines.append("")
    lines.append("local RowMeta = {")
    for field in model.client_fields:
        if field.type_text == "bool":
            lines.append(f"  {field.name} = function(s) return GD.I8(_tbl, {field.slot}, s) ~= 0 end,")
        elif field.type_text == "string":
            lines.append(f"  {field.name} = function(s) return GD.Str(_tbl, {field.slot}, s) end,")
        else:
            lines.append(f"  {field.name} = function(s) return GD.I32(_tbl, {field.slot}, s) end,")
    lines.append("}")
    lines.append("")
    lines.append("local M = {}")
    for index in model.indexes:
        if index.kind == "code":
            lines.append("-- exact-string Code lookup; nil when missing")
            lines.append(f"function M.ByCode(code) local row = GD.IndexCode(_tbl, {index.slot}, code) if row < 0 then return nil end return setmetatable({{_row = row}}, RowMeta) end")
        else:
            lines.append("-- Group lookup; returns rows in deterministic order")
            lines.append(f"function M.ByGroupKey(value) local rows = GD.IndexGroup(_tbl, {index.slot}, value) local out = {{}} for i = 1, #rows do out[i] = setmetatable({{_row = rows[i]}}, RowMeta) end return out end")
    lines.append(f"function M.ByID(id) return setmetatable({{_row = GD.ByID(_tbl, id)}}, RowMeta) end")
    lines.append("return M")
    return "\n".join(lines)


def render_csharp_accessor(table, indexes) -> str:
    return generate_csharp_accessor(build_accessor_model(table, indexes))


def render_lua_accessor(table, indexes) -> str:
    return generate_lua_accessor(build_accessor_model(table, indexes))


def _table():
    from ct.schema.resources import TableResource, FieldDef

    return TableResource(
        table="Item",
        primary="Id",
        fields=[
            FieldDef(name="Id", type="int32"),
            FieldDef(name="CodeName", type="string"),
            FieldDef(name="Category", type="int32"),
        ],
    )


def golden_csharp(table=None, indexes=None) -> str:
    if table is None:
        table = _table()
    if indexes is None:
        indexes = (QueryIndex(kind="code", field="CodeName"), QueryIndex(kind="group", field="Category"))
    return render_csharp_accessor(table, indexes)


def golden_lua(table=None, indexes=None) -> str:
    if table is None:
        table = _table()
    if indexes is None:
        indexes = (QueryIndex(kind="code", field="CodeName"), QueryIndex(kind="group", field="Category"))
    return render_lua_accessor(table, indexes)
