"""Generate {table}_accessor.lua files for each config table.

生成器产出**无状态访问器**（design D4）：

- 模块加载时经 ``GD.FindTable`` 取一次表句柄（C 固定槽位引用，跨加载有效）
- READERS 分发表：字段名 → 读取 lambda（slot = vtable 槽位 = 4 + 2*字段序）
- 行/struct 访问器 = 共享元表（make_meta 工厂），所有行共用一个元表
- 数组经 ``GD.Arr`` 返回带 ``__len/__index/__pairs`` 的视图
- 公开 API：ByID / ByIndex / Count（纯函数，无状态、无 preload）

字段读取约定（与原生 C 读取器、C# WireReader 对齐）：
- 标量按类型分派（I8/I32/I64/F32/F64）；bool 由 ``I8(...) ~= 0`` 组合
- string：i18n 字段经 ``GD.I18nStr`` 优先（i18n 表二分），未命中 ``GD.Str`` 兜底原文
- struct：``GD.Struct`` 返回嵌套表对象 userdata（挂 struct 访问器元表）
- array：``GD.Arr`` 返回视图（elemTag 由生成器按元素类型写死）
"""

from __future__ import annotations

from pathlib import Path

from ct.export.accessor_model import build_accessor_model
from ct.schema.models import FieldDef, TableSchema

# 元素类型 → gd 模块 elemTag（GD.Arr 的第二个参数）
_ELEM_TAGS = {
    "int32": "i32",
    "int64": "i64",
    "float": "f32",
    "double": "f64",
    "bool": "bool",
    "string": "str",
    "enum": "i8",
}

# 标量字段类型 → GD 读取函数
_SCALAR_READERS = {
    "int32": "GD.I32",
    "int64": "GD.I64",
    "float": "GD.F32",
    "double": "GD.F64",
    "enum": "GD.I8",
}


def _slot(idx: int) -> int:
    """vtable 槽位 = 4 + 2*字段序（flatbuffers 约定，与 C/C# 读取器一致）。"""
    return 4 + 2 * idx


def generate_lua_accessor(schema: TableSchema, output_dir: Path) -> Path:
    """Generate ``{table}_accessor.lua`` and write it to *output_dir*."""
    model = build_accessor_model(schema)
    output_dir.mkdir(parents=True, exist_ok=True)

    table_pascal = schema.table
    client_fields: list[FieldDef] = model.client_fields
    # 主键槽位（i18n 查询用）：按 schema 字段序计算
    pk_idx = next(i for i, f in enumerate(client_fields) if f.name == schema.primary)
    pk_slot = _slot(pk_idx)

    lines: list[str] = []
    w = lines.append

    # -- header ---------------------------------------------------------------
    w(f"-- Auto-generated by ct/export/lua_accessor_generator.py  DO NOT EDIT")
    w(f"-- Accessor for table: {schema.table}")
    w(f"--")
    w(f"-- Usage: local row = Config.{table_pascal}.ByID(id)")
    w(f"-- Fields:")
    for f in client_fields:
        flags = []
        if f.i18n:
            flags.append("i18n")
        flag_str = f", {', '.join(flags)}" if flags else ""
        w(f"--   .{f.name} ({f.type}{flag_str})")
    w("")
    w('local GD = require("gd")')
    w("")
    w("-- 表句柄：模块加载时取一次（C 固定槽位引用，跨加载有效）")
    w(f'local _tbl     = GD.FindTable("{schema.table}")')
    if schema.has_i18n:
        w(f'local _i18nTbl = GD.FindTableI18n("{schema.table}_i18n")')
    w("")
    w("-- 统一元表工厂：字段名 → 读取 lambda（READERS 分发表，一次性构建）")
    w("local function make_meta(readers)")
    w("    return { __index = function(self, key)")
    w("        local fn = readers[key]")
    w("        if fn then return fn(self) end")
    w("    end }")
    w("end")
    w("")

    # -- struct 访问器元表（每个 struct 字段一个） -----------------------------
    for f in client_fields:
        if f.type == "struct" and f.fields:
            w(f"-- struct 访问器元表（{f.name}；self = 嵌套表 userdata）")
            w(f"local {f.name}Meta = make_meta({{")
            for i, sf in enumerate(f.fields):
                w(f"    {sf.name} = function(s) return GD.I32(s, {_slot(i)}) end,")
            w("})")
            w("")

    # -- array 访问器元表（通用；elem 类型固化在视图 payload 里） -------------
    w("-- array 访问器元表（通用）")
    w("local ArrayMeta = {}")
    w("ArrayMeta.__len   = function(self) return GD.ArrLen(self) end")
    w("ArrayMeta.__index = function(self, i) return GD.ArrAt(self, i) end")
    w("ArrayMeta.__pairs = ipairs          -- 稠密向量，pairs ≡ ipairs")
    w("")

    # -- 行访问器元表：READERS 分发表 ----------------------------------------
    w("-- 行访问器元表（每表一个，所有行共用一个元表；self = 行 userdata）")
    w("local RowMeta = make_meta({")
    for i, f in enumerate(client_fields):
        slot = _slot(i)
        w(f"    {f.name} = function(s)")
        if f.type == "string" and f.i18n:
            w(f"        local v = GD.I18nStr(_i18nTbl, s, {pk_slot}, 4, {slot})")
            w(f"        return v ~= nil and v or GD.Str(s, {slot})")
        elif f.type == "bool":
            w(f"        return GD.I8(s, {slot}) ~= 0")
        elif f.type in _SCALAR_READERS:
            w(f"        return {_SCALAR_READERS[f.type]}(s, {slot})")
        elif f.type == "struct":
            w(f"        return GD.Struct(s, {slot}, {f.name}Meta)")
        elif f.type == "array":
            w(f'        return GD.Arr(s, {slot}, "{_ELEM_TAGS.get(f.element, "i32")}", ArrayMeta)')
        elif f.type == "string":
            w(f"        return GD.Str(s, {slot})")
        else:
            raise ValueError(f"表字段类型不支持: {f.type}")
        w(f"    end,")
    w("})")
    w("")

    # -- 公开 API --------------------------------------------------------------
    w("-- 公开 API（纯函数，无状态）")
    w("local M = {}")
    w("function M.ByID(id)")
    w("    return GD.ByID(_tbl, id, RowMeta)")
    w("end")
    w("function M.ByIndex(i)")
    w("    return GD.ByIndex(_tbl, i, RowMeta)")
    w("end")
    w("function M.Count()")
    w("    return GD.Count(_tbl)")
    w("end")
    w("")
    w("return M")
    w("")

    out_path = output_dir / f"{table_pascal}Accessor.lua"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return out_path
