// Whole-workspace backup/restore and rollback between two accepted native revisions.
// Everything mutable lives in a system temporary directory; never writes real gd.
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdtemp,cp,rename,readFile,writeFile,readdir,stat,utimes,rm,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
const args=process.argv.slice(2);function flag(name){const i=args.indexOf(name);if(i<0||!args[i+1])throw Error(name+' is required');return resolve(args[i+1])}
const current=flag('--current'),previous=flag('--previous'),out=flag('--out');const repo=resolve(import.meta.dirname,'../../..');
const root=await mkdtemp(join(tmpdir(),'ct-migration-drill-')),workspace=join(root,'工作区 with spaces'),backup=join(root,'full-backup');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');const commands=[];
function run(binary,command,expected=0){const args=[...command,'--root',workspace];const r=spawnSync(binary,args,{encoding:'utf8',timeout:120000});if(r.error)throw r.error;commands.push({binary,args,exit:r.status,stdout:r.stdout,stderr:r.stderr});if(r.status!==expected)throw Error('unexpected exit '+r.status+' '+r.stderr);return r}
async function snapshot(base,normalize=false,relative=''){const result={};for(const entry of await readdir(join(base,relative),{withFileTypes:true})){const name=relative?relative+'/'+entry.name:entry.name,p=join(base,name);if(entry.isDirectory())Object.assign(result,await snapshot(base,normalize,name));else{let info=await stat(p);if(normalize){const time=Math.floor(info.mtimeMs)/1000;await utimes(p,time,time);info=await stat(p)}const bytes=await readFile(p);result[name]={sha256:sha(bytes),bytes:bytes.length,mtimeMs:info.mtimeMs}}}return result}
function equal(a,b,mtime=true){if(JSON.stringify(Object.keys(a).sort())!==JSON.stringify(Object.keys(b).sort()))throw Error('file set differs');for(const key of Object.keys(a))if(a[key].sha256!==b[key].sha256||a[key].bytes!==b[key].bytes||(mtime&&Math.abs(a[key].mtimeMs-b[key].mtimeMs)>1))throw Error('backup/restore differs: '+key)}
await cp(join(repo,'native/fixtures/accessor_verify/workspace'),workspace,{recursive:true});
const paths={schemas_dir:['config/schemas','input schemas'],excel_dir:['excel','sheet files'],output_dir:['output','generated files'],cache_dir:['cache','private cache'],i18n_dir:['i18n','translation files']};let cfg=await readFile(join(workspace,'config/global.yaml'),'utf8');for(const[key,[oldName,newName]]of Object.entries(paths)){cfg=cfg.replace(new RegExp('^'+key+':.*$','m'),key+': '+JSON.stringify(newName));if(['schemas_dir','excel_dir','i18n_dir'].includes(key))await rename(join(workspace,oldName),join(workspace,newName))}await writeFile(join(workspace,'config/global.yaml'),cfg);await mkdir(join(workspace,'custom user'),{recursive:true});await writeFile(join(workspace,'custom user/notes.txt'),'User-owned extra data must survive a whole-workspace rollback.\n');
const binaries={current:{path:current,sha256:sha(await readFile(current))},previous:{path:previous,sha256:sha(await readFile(previous))}};
run(current,['export','--all']);const original=await snapshot(workspace,true);await cp(workspace,backup,{recursive:true,preserveTimestamps:true});equal(original,await snapshot(backup));
const lang=join(workspace,'translation files/en/Item.json'),entries=JSON.parse(await readFile(lang,'utf8'));entries['1.Name'].text='Upgrade drill translation';await writeFile(lang,JSON.stringify(entries,null,2)+'\n');run(current,['export','--all']);const upgraded=await snapshot(workspace);if(upgraded['generated files/binary/data_en.bin'].sha256===original['generated files/binary/data_en.bin'].sha256)throw Error('upgrade mutation did not change output');await writeFile(join(workspace,'custom user/new-after-upgrade.txt'),'This must be absent after restore');
await rm(workspace,{recursive:true});await cp(backup,workspace,{recursive:true,preserveTimestamps:true});equal(original,await snapshot(workspace));run(previous,['status']);equal(original,await snapshot(workspace));run(previous,['export','--all']);const rolledBack=await snapshot(workspace);for(const name of Object.keys(original).filter(x=>x.startsWith('generated files/')))if(original[name].sha256!==rolledBack[name]?.sha256)throw Error('previous native revision output mismatch: '+name);
// Unknown Apply is intentionally preserved and refuses recovery or mutation.
const unknown=join(workspace,'private cache/apply.journal.json');await writeFile(unknown,'{"format":"future-unknown-apply/99","userMaterial":"preserve"}\n');const beforeUnknown=await snapshot(workspace);run(current,['recover'],1);run(current,['gen-template','--table','Item'],1);equal(beforeUnknown,await snapshot(workspace));
await writeFile(out,JSON.stringify({schema:'ct-native-migration-drill/1',at:new Date().toISOString(),root,binaries,customPaths:paths,fullBackupFiles:Object.keys(original).length,backupAndRestoreBytesAndMtime:true,upgradeChangedBinary:true,previousNativeReadOnlyStatusPreservedWorkspace:true,previousNativeExportMatchesOriginal:true,unknownApplyRefusedWithoutFileChanges:true,commands},null,2)+'\n');console.log('Native backup/rollback/unknown-journal drill passed; evidence '+out);
