"""生成「定宽布局 + 字面量偏移」的 accessor，用于验证能否追平 参考实现 的单条 load。

前置：canonical_binary.build_canonical_table_bytes(uniform=True) 使同表所有行共享一个 vtable，
probe_row_layout() 给出表级常量 slot→offset。据此生成器可发射
``*(int*)(row + 60)`` —— 与 参考实现 的 ``p->field`` 同构，无偏移表间接层。

产出：
  fixtures/ItemBenchUniform.bin / ArrayBenchUniform.bin
  ItemBenchLiteral.g.cs / ArrayBenchLiteral.g.cs

用法：
  cd ct && .venv\\Scripts\\python test-proj\\RefConfigBench\\gen_literal_accessor.py
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
FIX = os.path.join(HERE, "fixtures")
sys.path.insert(0, os.path.join(ROOT, "ct", "src"))
sys.path.insert(0, HERE)

from ct.export.canonical_binary import build_canonical_table_bytes, probe_row_layout  # noqa: E402
from ct.schema.resources import FieldDef  # noqa: E402
from ct.schema.type_expression import NamedType, ScalarType, VectorType  # noqa: E402
from gen_ct_bench_tables import build_array_bench, build_item_bench  # noqa: E402

CS_SCALAR = {"int32": "int", "int64": "long", "float": "float", "double": "double", "bool": "bool"}


def getter(field: FieldDef, slot: int, expr: FieldDef = None) -> str | None:
    """返回字段的 getter 表达式（字面量偏移版）；不支持的返回 None。"""
    off = f"P + {expr[slot]}" if expr[slot] else None
    if off is None:
        return None
    kind = field.type_expr
    if isinstance(kind, ScalarType):
        if kind.name == "string":
            return f"new NString(P + {expr[slot]} + *(int*)(P + {expr[slot]}), _version)"
        if kind.name == "bool":
            return f"*(byte*)(P + {expr[slot]}) != 0"
        if kind.name == "float":
            return f"*(float*)(P + {expr[slot]})"
        if kind.name == "int64":
            return f"*(long*)(P + {expr[slot]})"
        if kind.name == "double":
            return f"*(double*)(P + {expr[slot]})"
        return f"*(int*)(P + {expr[slot]})"
    if isinstance(kind, VectorType):
        el = kind.element
        if isinstance(el, ScalarType) and el.name == "int32":
            return f"new NArray<int>(P + {expr[slot]} + *(int*)(P + {expr[slot]}), _version)"
        if isinstance(el, ScalarType) and el.name == "string":
            return f"new NStructArray<NString>(P + {expr[slot]} + *(int*)(P + {expr[slot]}), _version)"
        return None
    if isinstance(kind, NamedType) and kind.expected_kind == "enum":
        # 注意：必须写成 (T)(*(byte*)(...))。
        # 写成 (T)*(byte*)(...) 会被 C# 解析为「指向 T 的指针」→ CS0119 编译失败。
        return f"({kind.name})(*(byte*)(P + {expr[slot]}))"
    return None  # record 子行未纳入字面量变体（字段少，收益不抵复杂度）


def py_type(field: FieldDef) -> str:
    kind = field.type_expr
    if isinstance(kind, ScalarType):
        if kind.name == "string":
            return "string"
        return CS_SCALAR.get(kind.name, "int")
    if isinstance(kind, VectorType):
        el = kind.element
        if isinstance(el, ScalarType) and el.name == "string":
            return "NStructArray<NString>"
        return "NArray<int>"
    return kind.name  # enum


def emit(table, layout: dict[int, int], name: str) -> str:
    lines = [
        "// <auto-generated/> 定宽布局 + 字面量偏移（无偏移表间接层）",
        "using System;",
        "using System.Runtime.CompilerServices;",
        "",
        f"public static class {name}",
        "{",
        "    private static ConfigTable _table;",
        "    private static int _ver = -1;",
        "",
        "    internal static ConfigTable Table",
        "    {",
        "        get",
        "        {",
        "            ConfigTable t = _table;",
        "            if (t != null && _ver == TableVersion.Current) return t;",
        "            _table = Runtime.Table(TableName);",
        "            _ver = TableVersion.Current;",
        "            return _table;",
        "        }",
        "    }",
        f"    public const string TableName = \"{table.table}\";",
        "    public static int Count => Table.Count;",
        f"    public static {table.table}LiteralRow? ByID(int id)",
        "    {",
        "        ConfigTable t = Table;",
        "        IntPtr p = t.ByID(id);",
        "        return p == IntPtr.Zero ? null : new " + table.table + "LiteralRow(p, t.Version);",
        "    }",
        f"    public static {table.table}LiteralRow? ByIndex(int i)",
        "    {",
        "        ConfigTable t = Table;",
        "        IntPtr p = t.RowAt(i);",
        "        return p == IntPtr.Zero ? null : new " + table.table + "LiteralRow(p, t.Version);",
        "    }",
        "}",
        "",
        f"public unsafe readonly struct {table.table}LiteralRow",
        "{",
        "    private readonly IntPtr _row;",
        "    private readonly int _version;",
        f"    internal {table.table}LiteralRow(IntPtr row, int version) {{ _row = row; _version = version; }}",
        "    private byte* P => (byte*)_row;",
    ]
    for index, field in enumerate(table.fields):
        slot = 4 + 2 * index
        expr = getter(field, slot, layout)
        if expr is None:
            continue
        lines.append(f"    public {py_type(field)} {field.name} => {expr};")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    os.makedirs(FIX, exist_ok=True)
    for name, builder in (("ItemBench", build_item_bench), ("ArrayBench", build_array_bench)):
        table, records, enums, rows = builder()
        data = build_canonical_table_bytes(rows, table, records=records, enums=enums, uniform=True)
        with open(os.path.join(FIX, f"{name}Uniform.bin"), "wb") as fh:
            fh.write(data)
        layout = probe_row_layout(table, records=records, enums=enums)
        cs = emit(table, layout, f"{name}LiteralAccessor")
        with open(os.path.join(HERE, f"{name}Literal.g.cs"), "w", encoding="utf-8") as fh:
            fh.write(cs)
        print(f"{name}Uniform.bin: {len(data):,} 字节   vtable=1   字面量访问器 {len(cs):,} 字符")
        print("   layout:", {f.name: layout[4 + 2 * i] for i, f in enumerate(table.fields)})


if __name__ == "__main__":
    main()
